// ignore_for_file: avoid_print
/// Batch 3 seed expansion: 100 → 220 works (서브컬처 비중 ~85%)
/// Usage: dart run tool/seed_expansion_batch3.dart

import 'dart:convert';
import 'dart:io';

void main() {
  final projectRoot = _findProjectRoot();
  final shardsRoot = Directory('${projectRoot.path}/akasha-db/shards');
  final seeds = _batch3Seeds();

  var added = 0;
  var skipped = 0;

  for (final seed in seeds) {
    final workId = seed['workId'] as String;
    final shardId = _shardIdFor(workId);
    final category = seed['category'] as String;
    final shardPath = '${shardsRoot.path}/$category/${shardId}.json';
    final shardFile = File(shardPath);

    Map<String, dynamic> shardMap = {};
    if (shardFile.existsSync()) {
      final decoded = json.decode(shardFile.readAsStringSync());
      if (decoded is Map<String, dynamic>) {
        shardMap = Map<String, dynamic>.from(decoded);
      }
    }

    if (shardMap.containsKey(workId)) {
      print('SKIP duplicate: $workId');
      skipped++;
      continue;
    }

    shardMap[workId] = seed;
    shardFile.parent.createSync(recursive: true);
    shardFile.writeAsStringSync(
      '${const JsonEncoder.withIndent('  ').convert(shardMap)}\n',
    );
    print('ADD $workId → $category/$shardId.json');
    added++;
  }

  print('\nDone: $added added, $skipped skipped');
}

String _shardIdFor(String workId) {
  final parts = workId.split('_');
  if (parts.length < 4) return 'misc';
  final category = parts[1];
  final identifier = parts[2];

  if (category == 'game' && identifier.startsWith('appid')) {
    final appId = identifier.replaceFirst('appid', '');
    return 'game_steam_$appId';
  }

  if (category == 'manga' && RegExp(r'^\d').hasMatch(identifier)) {
    return 'manga_numeric';
  }

  final letter = identifier.isNotEmpty ? identifier[0].toUpperCase() : 'X';
  return '${category}_$letter';
}

Directory _findProjectRoot() {
  var dir = Directory.current;
  while (true) {
    if (File('${dir.path}/pubspec.yaml').existsSync()) return dir;
    final parent = dir.parent;
    if (parent.path == dir.path) return Directory.current;
    dir = parent;
  }
}

String _ani(int id, {bool anime = false}) {
  final kind = anime ? 'anime' : 'manga';
  return 'https://s4.anilist.co/file/anilistcdn/media/$kind/cover/large/bx$id.jpg';
}

String _steam(int appId) =>
    'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/$appId/library_600x900.jpg';

String _tmdb(String path) => 'https://image.tmdb.org/t/p/w500$path';

String _openLib(String isbn) =>
    'https://covers.openlibrary.org/b/isbn/$isbn-L.jpg';

String _igdb(String hash) =>
    'https://images.igdb.com/igdb/image/upload/t_cover_big/$hash.jpg';

List<Map<String, dynamic>> _batch3Seeds() => [
      // ── MANGA (+42, subculture) ──
      _w('sub_manga_tokyo-ghoul_2011', '도쿄 구울', 'manga', 'subculture', '이시다 슈이', 2011,
          '인간을 사냥하는 구울이 된 대학생의 어두운 서울 생존기.',
          ['다크', '액션', '호러', '서울'], _ani(30054)),
      _w('sub_manga_black-clover_2015', '블랙 클로버', 'manga', 'subculture', '타바타 유키', 2015,
          '마법이 없는 소년이 마법제 최강을 꿈꾸는 판타지 배틀.',
          ['판타지', '마법', '액션', '우정'], _ani(86337)),
      _w('sub_manga_vinland-saga_2005', '빈란드 사가', 'manga', 'subculture', '야마다코', 2005,
          '바이킹 시대를 배경으로 한 복수와 성장의 서사시.',
          ['역사', '액션', '복수', '성장'], _ani(34825)),
      _w('sub_manga_kingdom_2006', '킹덤', 'manga', 'subculture', '하라 야스히사', 2006,
          '춘추전국시대 중국을 배경으로 한 대규모 전쟁 서사.',
          ['역사', '전쟁', '전략', '성장'], _ani(44347)),
      _w('sub_manga_gintama_2003', '은혼', 'manga', 'subculture', '소라타히로', 2003,
          '에도 말기 외계인과 사무라이들의 유쾌한 코믹 액션.',
          ['코미디', '사무라이', 'SF', '패러디'], _ani(30044)),
      _w('sub_manga_fairy-tail_2006', '페어리 테일', 'manga', 'subculture', '마시마 히로', 2006,
          '마법 길드 페어리 테일의 모험과 우정 이야기.',
          ['판타지', '마법', '길드', '우정'], _ani(30694)),
      _w('sub_manga_parasyte_1990', '기생수', 'manga', 'subculture', '이와와키 히토시', 1990,
          '손에 기생한 외계 생명체와 공존하며 인류를 지키는 이야기.',
          ['SF', '호러', '철학', '액션'], _ani(30045)),
      _w('sub_manga_golden-kamuy_2014', '골든 카무이', 'manga', 'subculture', '나츠미 소이치', 2014,
          '홋카이도에서 금 보물을 찾는 아이누와 전직 군인의 모험.',
          ['역사', '모험', '서바이벌', '코미디'], _ani(86559)),
      _w('sub_manga_hells-paradise_2018', '지옥락', 'manga', 'subculture', '가쿠 쿠지', 2018,
          '사형수들이 불멸의 약을 찾기 위해 지옥섬에 들어가는 이야기.',
          ['액션', '닌자', '판타지', '서바이벌'], _ani(101348)),
      _w('sub_manga_promised-neverland_2016', '약속의 네버랜드', 'manga', 'subculture', '시라이 카이', 2016,
          '고아원 아이들이 숨겨진 진실을 알게 된 뒤 탈출을 꾸미는 스릴러.',
          ['스릴러', '미스터리', '탈출', '다크'], _ani(99624)),
      _w('sub_manga_horimiya_2011', '호리미야', 'manga', 'subculture', '하기와라 히로', 2011,
          '학교와 집에서 다른 모습을 보이는 두 학생의 로맨스.',
          ['로맨스', '학원', '코미디', '일상'], _ani(122633)),
      _w('sub_manga_kaguya-sama_2015', '카구야님은 고백받고 싶어', 'manga', 'subculture',
          '아카사카 아카', 2015,
          '서로 고백받기 위해 두뇌 싸움을 벌이는 학생회장 커플의 로맨스 코미디.',
          ['로맨스', '코미디', '학원', '두뇌전'], _ani(101921)),
      _w('sub_manga_quintessential-quintuplets_2017', '5등분의 신부', 'manga',
          'subculture', '하루카와 하루키', 2017,
          '쌍둥이 다섯 자매를 가르치는 과외 선생님의 로맨스.',
          ['로맨스', '코미디', '학원', '하렘'], _ani(103635)),
      _w('sub_manga_oshi-no-ko_2020', '최애의 아이', 'manga', 'subculture', '아카사카 아카', 2020,
          '연예계를 배경으로 한 환생과 복수, 성장의 드라마.',
          ['연예', '드라마', '미스터리', '복수'], _ani(120377)),
      _w('sub_manga_bocchi-the-rock_2017', '봇치 더 록!', 'manga', 'subculture', '하마다 쿠키', 2017,
          '내향적인 소녀가 밴드 활동을 통해 성장하는 음악 코미디.',
          ['음악', '코미디', '성장', '밴드'], _ani(109099)),
      _w('sub_manga_sakamoto-days_2020', '사카모토 데이즈', 'manga', 'subculture', '스즈키 유우', 2020,
          '전설의 킬러가 평범한 가족 생활을 지키기 위해 싸우는 액션 코미디.',
          ['액션', '코미디', '킬러', '가족'], _ani(128893)),
      _w('sub_manga_undead-unluck_2020', '언데드 언럭', 'manga', 'subculture', '토가시 토시히사', 2020,
          '불사와 불운 능력자가 세계 멸망을 막기 위해 맞서는 액션.',
          ['액션', '초능력', 'SF', '코미디'], _ani(127053)),
      _w('sub_manga_blue-period_2017', '블루 피리어드', 'manga', 'subculture', '야마다코', 2017,
          '미술에 빠진 소년이 도쿄 미대 입시를 향해 달리는 성장 이야기.',
          ['미술', '성장', '청춘', '드라마'], _ani(124080)),
      _w('sub_manga_monster_1994', '몬스터', 'manga', 'subculture', '우라사와 나오키', 1994,
          '의사가 구한 소년이 연쇄살인마로 성장하며 벌어지는 심리 스릴러.',
          ['스릴러', '심리', '범죄', '명작'], _ani(30019)),
      _w('sub_manga_20th-century-boys_1999', '20세기 소년', 'manga', 'subculture',
          '우라사와 나오키', 1999,
          '어릴 적 음모와 세계 파멸을 둘러싼 미스터리 서사.',
          ['미스터리', '음모', 'SF', '명작'], _ani(30039)),
      _w('sub_manga_pluto_2003', '플루토', 'manga', 'subculture', '우라사와 나오키', 2003,
          '로봇과 인간이 공존하는 미래의 연쇄 살인 추적 스릴러.',
          ['SF', '로봇', '스릴러', '명작'], _ani(30735)),
      _w('sub_manga_yu-yu-hakusho_1990', '유유백서', 'manga', 'subculture', '토가시 요시히로', 1990,
          '소년이 영계 탐정이 되어 요괴와 싸우는 액션 판타지.',
          ['액션', '요괴', '판타지', '명작'], _ani(30031)),
      _w('sub_manga_rurouni-kenshin_1994', '루론검심', 'manga', 'subculture', '와츠키 노부히로', 1994,
          '메이지 시대를 배경으로 한 비검살 검객의 여정.',
          ['사무라이', '역사', '액션', '로맨스'], _ani(30018)),
      _w('sub_manga_cardcaptor-sakura_1996', '카드캡터 체리', 'manga', 'subculture',
          'CLAMP', 1996,
          '마법 카드를 수집하는 소녀의 판타지 모험.',
          ['판타지', '마법', '소녀', '순정'], _ani(30073)),
      _w('sub_manga_fruits-basket_1998', '후르츠 바스켓', 'manga', 'subculture', '타카야 나츠키', 1998,
          '십이지 신의 저주에 걸린 소년과 가족들의 로맨스 판타지.',
          ['로맨스', '판타지', '힐링', '가족'], _ani(30026)),
      _w('sub_manga_nana_2000', 'NANA', 'manga', 'subculture', '야자와 아이', 2000,
          '같은 이름을 가진 두 여성의 우정과 사랑, 꿈을 그린 청춘 드라마.',
          ['로맨스', '음악', '청춘', '드라마'], _ani(30014)),
      _w('sub_manga_chihayafuru_2007', '치하야후루', 'manga', 'subculture', '스에마스 치카', 2007,
          '경쟁 카루타를 통해 성장하는 청춘 스포츠 로맨스.',
          ['스포츠', '카루타', '청춘', '로맨스'], _ani(10800)),
      _w('sub_manga_march-comes-in-like-a-lion_2007', '3월의 라이온', 'manga',
          'subculture', '우메자와 하토', 2007,
          '고독한 장기 기사가 가족과 만나 마음을 치유하는 성장 드라마.',
          ['장기', '성장', '힐링', '드라마'], _ani(21366)),
      _w('sub_manga_oregairu_2011', '내가 친구가 적은 건 아무래도 내가 멋진 고양이인 탓인가',
          'manga', 'subculture', '와타리 와타루', 2011,
          '봉사부에 끌려간 고독한 소년의 학원 코미디 드라마.',
          ['학원', '코미디', '드라마', '청춘'], _ani(14813)),
      _w('sub_manga_mushoku-tensei_2014', '무직전생', 'manga', 'subculture', '리덕션 / 후지카와 유카', 2014,
          '전생한 소년이 마법 세계에서 새 삶을 시작하는 이세계 판타지.',
          ['이세계', '판타지', '성장', '마법'], _ani(108465)),
      _w('sub_manga_tensura_2014', '전생했더니 슬라임이었던 건', 'manga', 'subculture',
          '후세이 / 미와타리', 2014,
          '슬라임으로 전생한 주인공이 나라를 건설하는 이세계 판타지.',
          ['이세계', '판타지', '슬라임', '건국'], _ani(101280)),
      _w('sub_manga_mushishi_1999', '충사', 'manga', 'subculture', '요시나가 루리', 1999,
          '맹(蟲)을 다루는 충사의 오묘한 여행담.',
          ['판타지', '오컬트', '단편', '힐링'], _ani(30091)),
      _w('sub_manga_toradora_2007', '토라도라!', 'manga', 'subculture', '타카에마시 유우', 2007,
          '까칠한 소녀와 소심한 소년이 연인 연기를 하며 벌어지는 로맨스.',
          ['로맨스', '코미디', '학원', '청춘'], _ani(4224)),
      _w('sub_manga_nisekoi_2011', '니세코이', 'manga', 'subculture', '칸노 코스키', 2011,
          '라이벌 조직 자녀들이 연인 연기를 하며 벌어지는 로맨스 코미디.',
          ['로맨스', '코미디', '학원', '하렘'], _ani(16664)),
      _w('sub_manga_goodnight-punpun_2007', '잘 자 뚱뚱이', 'manga', 'subculture', '아사노 이네', 2007,
          '평범해 보이는 소년의 성장과 붕괴를 그린 청춘 심리 드라마.',
          ['심리', '청춘', '드라마', '다크'], _ani(34646)),
      _w('sub_manga_real_1999', 'REAL', 'manga', 'subculture', '이노우에 다케히코', 1999,
          '휠체어 농구를 통해 삶을 재건하는 청소년들의 성장 스포츠 드라마.',
          ['스포츠', '농구', '성장', '드라마'], _ani(30895)),
      _w('sub_manga_ao-ashi_2015', '아오아시', 'manga', 'subculture', '우에소 유우', 2015,
          '에이스 공격수가 J리그 프로를 꿈꾸는 축구 성장 드라마.',
          ['스포츠', '축구', '성장', '청춘'], _ani(110229)),
      _w('sub_manga_skip-and-loafer_2018', '스킵과 로퍼', 'manga', 'subculture', '타카무라 마시무', 2018,
          '시골 소녀가 도쿄 명문고에 입학하며 겪는 청춘 성장기.',
          ['청춘', '학원', '성장', '코미디'], _ani(124195)),
      _w('sub_manga_dorohedoro_2000', '도로헤도로', 'manga', 'subculture', '하야시 카이', 2000,
          '마법사 머리를 가진 남자가 정체를 찾는 다크 판타지 액션.',
          ['다크', '판타지', '액션', '코미디'], _ani(33427)),
      _w('sub_manga_beastars_2016', 'BEASTARS', 'manga', 'subculture', '이토 파루', 2016,
          '육식·초식 동물이 공존하는 세계의 학원 드라마.',
          ['학원', '드라마', '동물', '로맨스'], _ani(107660)),
      _w('sub_manga_tower-of-god_2010', '신의 탑', 'manga', 'subculture',
          'SIU', 2010,
          '신의 탑을 오르며 비밀을 밝히는 소년의 판타지 모험.',
          ['판타지', '모험', '웹툰', '미스터리'], _ani(101573)),

      // ── ANIMATION (+30, subculture 중심) ──
      _w('sub_animation_attack-on-titan_2013', '진격의 거인', 'animation', 'subculture',
          'WIT STUDIO / MAPPA', 2013,
          '거대한 벽 너머의 거인과 맞서는 인류의 생존 액션.',
          ['액션', '다크', '미스터리', '명작'], _ani(16498, anime: true)),
      _w('sub_animation_one-punch-man_2015', '원펀맨', 'animation', 'subculture',
          'MADHOUSE', 2015,
          '한 방에 적을 쓰러뜨리는 히어로의 유쾌한 액션 코미디.',
          ['액션', '코미디', '히어로', '패러디'], _ani(21087, anime: true)),
      _w('sub_animation_mob-psycho-100_2016', '모브 사이코 100', 'animation',
          'subculture', 'BONES', 2016,
          '강력한 초능력 소년의 성장과 청소부 일상을 그린 액션.',
          ['초능력', '액션', '코미디', '성장'], _ani(21507, anime: true)),
      _w('sub_animation_noragami_2014', '노라가미', 'animation', 'subculture', 'BONES', 2014,
          '가난한 신이 소녀와 함께 소원을 들어주며 성장하는 판타지.',
          ['판타지', '신', '액션', '코미디'], _ani(20447, anime: true)),
      _w('sub_animation_made-in-abyss_2017', '메이드 인 어비스', 'animation',
          'subculture', 'Kinema Citrus', 2017,
          '거대한 구덩이를 탐험하는 소녀와 로봇의 다크 판타지 모험.',
          ['판타지', '모험', '다크', '명작'], _ani(97986, anime: true)),
      _w('sub_animation_mushoku-tensei_2021', '무직전생', 'animation', 'subculture',
          'Studio Bind', 2021,
          '전생한 소년이 마법 세계에서 새 삶을 사는 이세계 판타지.',
          ['이세계', '판타지', '성장', '마법'], _ani(114065, anime: true)),
      _w('sub_animation_oshi-no-ko_2023', '최애의 아이', 'animation', 'subculture',
          'Doga Kobo', 2023,
          '연예계의 환생과 음모를 그린 드라마 애니메이션.',
          ['연예', '드라마', '미스터리', '복수'], _ani(150672, anime: true)),
      _w('sub_animation_bocchi-the-rock_2022', '봇치 더 록!', 'animation',
          'subculture', 'CloverWorks', 2022,
          '내향적 소녀의 밴드 성장기를 그린 음악 코미디.',
          ['음악', '코미디', '밴드', '성장'], _ani(146065, anime: true)),
      _w('sub_animation_bungo-stray-dogs_2016', '문호 스트레이 독스', 'animation',
          'subculture', 'BONES', 2016,
          '문호 능력을 가진 탐정들의 초능력 액션.',
          ['액션', '초능력', '문학', '미스터리'], _ani(21311, anime: true)),
      _w('sub_animation_psycho-pass_2012', '사이코 패스', 'animation', 'subculture',
          'Production I.G', 2012,
          '범죄 수치로 사회를 통제하는 디스토피아 SF 수사극.',
          ['SF', '스릴러', '디스토피아', '수사'], _ani(13601, anime: true)),
      _w('sub_animation_samurai-champloo_2004', '사무라이 참프루', 'animation',
          'subculture', 'Manglobe', 2004,
          '에도 시대 힙합 무협을 그린 유쾌한 사무라이 로드무비.',
          ['사무라이', '액션', '힙합', '로드무비'], _ani(205, anime: true)),
      _w('sub_animation_trigun_1998', '트라이건', 'animation', 'subculture', 'MADHOUSE', 1998,
          '현상금 사냥꾼을 쫓는 총잡이의 SF 서부 액션.',
          ['SF', '액션', '코미디', '명작'], _ani(6, anime: true)),
      _w('sub_animation_hajime-no-ippo_2000', '첫걸음', 'animation', 'subculture',
          'MADHOUSE', 2000,
          '소심한 소년이 복싱을 통해 강해지는 스포츠 성장 드라마.',
          ['스포츠', '복싱', '성장', '청춘'], _ani(263, anime: true)),
      _w('sub_animation_gintama_2006', '은혼', 'animation', 'subculture', 'SUNRISE', 2006,
          '에도 말기 외계인과 사무라이의 유쾌한 코믹 액션.',
          ['코미디', '사무라이', 'SF', '패러디'], _ani(918, anime: true)),
      _w('sub_animation_black-lagoon_2006', '블랙 라군', 'animation', 'subculture',
          'MADHOUSE', 2006,
          '동남아 해적과 용병들의 거친 액션 스릴러.',
          ['액션', '총기', '스릴러', '성인'], _ani(889, anime: true)),
      _w('sub_animation_monogatari_2009', '바케모노가타리', 'animation', 'subculture',
          'SHAFT', 2009,
          '괴물과 인간의 이야기를 풀어가는 대화 중심 초자연 시리즈.',
          ['초자연', '로맨스', '대화', '명작'], _ani(5081, anime: true)),
      _w('sub_animation_rezero-anime_2016', 'Re:제로', 'animation', 'subculture',
          'WHITE FOX', 2016,
          '이세계에서 죽음을 반복하며 운명을 바꾸려는 소년의 이야기.',
          ['이세계', '루프', '판타지', '드라마'], _ani(21355, anime: true)),
      _w('sub_animation_konosuba_2016', '이 멋진 세계에 축복을!', 'animation',
          'subculture', 'Studio Deen', 2016,
          '최약 직업으로 이세계에 소환된 소년의 코믹 판타지.',
          ['이세계', '코미디', '판타지', '패러디'], _ani(21202, anime: true)),
      _w('sub_animation_overlord_2015', '오버로드', 'animation', 'subculture',
          'MADHOUSE', 2015,
          '게임이 종료된 뒤 NPC로 남은 최종 보스의 이세계 정복기.',
          ['이세계', '판타지', '악역', '전략'], _ani(20832, anime: true)),
      _w('sub_animation_slime-anime_2018', '전생 슬라임', 'animation', 'subculture',
          '8bit', 2018,
          '슬라임으로 전생한 주인공의 이세계 건국 판타지.',
          ['이세계', '판타지', '슬라임', '건국'], _ani(101280, anime: true)),
      _w('sub_animation_shield-hero_2019', '방패 용사 성공담', 'animation',
          'subculture', 'Kinema Citrus', 2019,
          '배신당한 방패 용사가 세계를 구원해 나가는 이세계 판타지.',
          ['이세계', '판타지', '복수', '성장'], _ani(99624, anime: true)),
      _w('sub_animation_clannad_2007', '클라나드', 'animation', 'subculture',
          'Kyoto Animation', 2007,
          '가족과 사랑, 상실을 그린 감동 학원 드라마.',
          ['감동', '학원', '가족', '로맨스'], _ani(2167, anime: true)),
      _w('sub_animation_angel-beats_2010', '엔젤 비츠!', 'animation', 'subculture',
          'P.A.Works', 2010,
          '사후 세계 학교에서 벌어지는 청춘과 이별의 이야기.',
          ['학원', '감동', '판타지', '음악'], _ani(6547, anime: true)),
      _w('sub_animation_silent-voice_2016', '목소리의 형태', 'animation',
          'subculture', 'Kyoto Animation', 2016,
          '청각장애 소녀와 전학생의 화해와 성장을 그린 감동 영화.',
          ['감동', '청춘', '학원', '영화'], _ani(20954, anime: true)),
      _w('sub_animation_weathering-with-you_2019', '날씨의 아이', 'animation',
          'subculture', 'CoMix Wave Films', 2019,
          '비를 막는 소녀와 소년의 도쿄 판타지 로맨스.',
          ['로맨스', '판타지', '영화', '신카이'], _ani(106286, anime: true)),
      _w('sub_animation_ping-pong_2014', '핑퐁', 'animation', 'subculture', 'TMS', 2014,
          '탁구 소년들의 청춘과 재능을 그린 스포츠 드라마.',
          ['스포츠', '탁구', '청춘', '드라마'], _ani(20707, anime: true)),
      _w('sub_animation_dandadan-anime_2024', '단다단', 'animation', 'subculture',
          'Science SARU', 2024,
          '오컬트와 로봇이 뒤섞인 기묘한 청춘 배틀 코미디.',
          ['오컬트', '코미디', '액션', '청춘'], _ani(171018, anime: true)),
      _w('sub_animation_fate-zero_2011', '페이트/제로', 'animation', 'subculture',
          'ufotable', 2011,
          '성배전쟁을 둘러싼 마술사들의 비극적 서사.',
          ['판타지', '마술', '전쟁', '명작'], _ani(10087, anime: true)),
      _w('sub_animation_lycoris-recoil_2022', '리코리스 리코일', 'animation',
          'subculture', 'A-1 Pictures', 2022,
          '카페 직원이자 비밀 요원 두 소녀의 액션 드라마.',
          ['액션', '총기', '일상', '배틀'], _ani(143270, anime: true)),
      _w('sub_animation_cyberpunk-edgerunners_2022', '사이버펑크: 엣지러너',
          'animation', 'subculture', 'Studio Trigger', 2022,
          '나이트 시티에서 살아남으려는 사이버펑크 청춘의 비극.',
          ['사이버펑크', '액션', 'SF', '다크'], _ani(120377, anime: true)),

      // ── GAME (+30, subculture 22 / general 8) ──
      _w('sub_game_persona-5-royal_2020', '페르소나 5 로열', 'game', 'subculture',
          'Atlus', 2020,
          '마스크를 쓴 도둑단이 심장의 궁전을 훔치는 JRPG.',
          ['JRPG', '학원', '스타일', '서브컬처'], _steam(1687950)),
      _w('sub_game_nier-automata_2017', '니어: 오토마타', 'game', 'subculture',
          'PlatinumGames', 2017,
          '안드로이드 전투원이 인류를 위해 싸우는 액션 RPG.',
          ['액션', 'SF', '철학', '명작'], _steam(524220)),
      _w('sub_game_ffxiv_2013', '파이널 판타지 XIV', 'game', 'subculture',
          'Square Enix', 2013,
          '에오르제아 대륙을 배경으로 한 대규모 MMORPG.',
          ['MMORPG', '판타지', '스토리', '협동'], _steam(39210)),
      _w('sub_game_arknights_2019', '명일방주', 'game', 'subculture', 'Hypergryph', 2019,
          '오퍼레이터를 배치해 감염체를 막는 타워 디펜스 전략.',
          ['타워디펜스', '전략', 'SF', '수집'], _igdb('co2l7z')),
      _w('sub_game_fate-grand-order_2015', '페이트/그랜드 오더', 'game', 'subculture',
          'TYPE-MOON / Aniplex', 2015,
          '성배전쟁을 둘러싼 서번트 수집형 RPG.',
          ['수집형RPG', '판타지', '서번트', '서브컬처'], _igdb('co1wyy')),
      _w('sub_game_fire-emblem-three-houses_2019', '파이어 엠블렘: 풍화설월',
          'game', 'subculture', 'Intelligent Systems', 2019,
          '전술 SRPG로 학원에서 세 가지 학급의 운명을 이끈다.',
          ['SRPG', '전술', '학원', '판타지'], _igdb('co49wj')),
      _w('sub_game_yakuza-0_2015', '용과 같이 0', 'game', 'subculture', 'Ryu Ga Gotoku Studio', 2015,
          '20세기 가오리호시에서 벌어지는 야쿠자 오리진 액션 어드벤처.',
          ['액션', '야쿠자', '스토리', '일본'], _steam(638970)),
      _w('sub_game_monster-hunter-world_2018', '몬스터 헌터: 월드', 'game',
          'subculture', 'CAPCOM', 2018,
          '거대 몬스터를 사냥하는 협동 액션 RPG.',
          ['액션', '협동', '헌팅', '판타지'], _steam(582010)),
      _w('sub_game_project-sekai_2020', '프로젝트 세카이', 'game', 'subculture',
          'Colorful Palette / SEGA', 2020,
          '버추얼 싱어와 함께 음악과 스토리를 즐기는 리듬 RPG.',
          ['리듬', '음악', '보컬로이드', '서브컬처'], _igdb('co2kgk')),
      _w('sub_game_umamusume_2021', '우마무스메', 'game', 'subculture', 'Cygames', 2021,
          '레이스마를 육성하는 수집형 육성 시뮬레이션.',
          ['육성', '경마', '수집', '서브컬처'], _igdb('co3p2z')),
      _w('sub_game_princess-connect_2018', '프린세스 커넥트', 'game', 'subculture',
          'Cygames', 2018,
          '왕녀와 동료를 모아 모험하는 수집형 RPG.',
          ['수집형RPG', '판타지', '코미디', '서브컬처'], _igdb('co1tmu')),
      _w('sub_game_zenless-zone-zero_2024', '젠레스 존 제로', 'game', 'subculture',
          'HoYoverse', 2024,
          '공동구역을 탐험하는 액션 RPG.',
          ['액션', 'SF', '도시', '서브컬처'], _igdb('co7j43')),
      _w('sub_game_wuthering-waves_2024', '명조: 워더링 웨이브', 'game', 'subculture',
          'Kuro Games', 2024,
          '잔향을 수집하며 모험하는 오픈월드 액션 RPG.',
          ['오픈월드', '액션', 'SF', '서브컬처'], _igdb('co7k5k')),
      _w('sub_game_danganronpa_2010', '단간론파', 'game', 'subculture', 'Spike Chunsoft', 2010,
          '학원에서 벌어지는 학급재판 미스터리 어드벤처.',
          ['미스터리', '어드벤처', '학원', '서브컬처'], _steam(413410)),
      _w('sub_game_stardew-valley-sub_2016', '스타듀 밸리', 'game', 'subculture',
          'ConcernedApe', 2016,
          '농장을 가꾸며 마을과 교감하는 힐링 시뮬레이션.',
          ['시뮬', '농장', '힐링', '인디'], _steam(413150)),
      _w('sub_game_undertale_2015', '언더테일', 'game', 'subculture', 'Toby Fox', 2015,
          '선택에 따라 결말이 달라지는 인디 RPG 명작.',
          ['인디', 'RPG', '선택', '명작'], _steam(391540)),
      _w('sub_game_celeste_2018', '셀레스테', 'game', 'subculture', 'Maddy Makes Games', 2018,
          '산 정상을 향한 플랫포머와 마음의 성장 이야기.',
          ['인디', '플랫포머', '난이도', '힐링'], _steam(504230)),
      _w('sub_game_octopath-traveler_2018', '옥토패스 트래블러', 'game', 'subculture',
          'Square Enix', 2018,
          '여덟 여행자의 HD-2D 판타지 여정.',
          ['JRPG', '판타지', 'HD-2D', '서브컬처'], _steam(921570)),
      _w('sub_game_xenoblade-3_2022', '제노블레이드 3', 'game', 'subculture',
          'Monolith Soft', 2022,
          '두 세계가 맞닿은 미래를 배경으로 한 대서사 JRPG.',
          ['JRPG', 'SF', '판타지', '서브컬처'], _igdb('co5s52')),
      _w('sub_game_splatoon-3_2022', '스플래툰 3', 'game', 'subculture', 'Nintendo', 2022,
          '먹물 슈터로 팀 대전을 즐기는 액션 게임.',
          ['슈터', '액션', '팀전', '서브컬처'], _igdb('co5k1z')),
      _w('sub_game_touhou-lost-word_2019', '동방 로스트 워드', 'game', 'subculture',
          'Team Shanghai Alice', 2019,
          '동방 프로젝트 세계관의 탄막 슈팅 RPG.',
          ['슈팅', '동방', '판타지', '서브컬처'], _igdb('co1rcz')),
      _w('sub_game_love-live-all-stars_2020', '러브라이브! 올스타즈', 'game',
          'subculture', 'KLab', 2020,
          '스쿨 아이돌을 육성하는 리듬 수집형 게임.',
          ['리듬', '아이돌', '수집', '서브컬처'], _igdb('co2k8k')),
      _w('gen_game_witcher-3_2015', '더 위처 3: 와일드 헌트', 'game',
          'generalCulture', 'CD PROJEKT RED', 2015,
          '괴물 사냥꾼 게롤트의 오픈월드 판타지 RPG.',
          ['오픈월드', 'RPG', '판타지', '명작'], _steam(292030)),
      _w('gen_game_skyrim_2011', '더 엘더스크롤 V: 스카이림', 'game',
          'generalCulture', 'Bethesda', 2011,
          '드래곤과 용맹한 자의 전설을 쓰는 오픈월드 RPG.',
          ['오픈월드', 'RPG', '판타지', '명작'], _steam(489830)),
      _w('gen_game_portal-2_2011', '포털 2', 'game', 'generalCulture', 'Valve', 2011,
          '포털 건으로 퍼즐을 푸는 SF 코미디 명작.',
          ['퍼즐', 'SF', '코미디', '명작'], _steam(620)),
      _w('gen_game_half-life-2_2004', '하프라이프 2', 'game', 'generalCulture', 'Valve', 2004,
          '억압 체제에 맞서는 SF FPS 명작.',
          ['FPS', 'SF', '명작', '스토리'], _steam(220)),
      _w('gen_game_bioshock_2007', '바이오쇼크', 'game', 'generalCulture', 'Irrational Games', 2007,
          '수중 도시 루테르시아의 비밀을 파헤치는 SF FPS.',
          ['FPS', 'SF', '철학', '명작'], _steam(7670)),
      _w('gen_game_mass-effect-2_2010', '매스 이펙트 2', 'game', 'generalCulture',
          'BioWare', 2010,
          '은하계를 구하기 위한 크루를 모으는 SF RPG.',
          ['SF', 'RPG', '스토리', '선택'], _steam(24980)),
      _w('gen_game_diablo-4_2023', '디아블로 IV', 'game', 'generalCulture', 'Blizzard', 2023,
          '어둠의 세계에서 악마를 토벌하는 핵앤슬래시 RPG.',
          ['핵앤슬래시', 'RPG', '다크', '온라인'], _steam(2344520)),
      _w('gen_game_overwatch-2_2022', '오버워치 2', 'game', 'generalCulture', 'Blizzard', 2022,
          '영웅 기반 팀 대전 슈터.',
          ['FPS', '팀전', '히어로', 'PvP'], _steam(2357570)),

      // ── BOOK (+12, subculture 9 / general 3) ──
      _w('sub_book_overlord-light-novel_2012', '오버로드', 'book', 'subculture',
          '칸나카', 2012,
          '게임이 끝난 뒤 NPC로 남은 최종 보스의 이세계 정복기 원작.',
          ['라이트노벨', '이세계', '판타지', '서브컬처'], _ani(85934)),
      _w('sub_book_konosuba-light-novel_2013', '이 멋진 세계에 축복을!', 'book',
          'subculture', '아카츠키 나츠메', 2013,
          '최약 직업으로 소환된 카즈마의 코믹 이세계 모험 원작.',
          ['라이트노벨', '이세계', '코미디', '서브컬처'], _ani(21202)),
      _w('sub_book_no-game-no-life_2011', '노 게임 노 라이프', 'book', 'subculture',
          '카무라', 2011,
          '게임만이 세계의 법인 판타지 세계에서 이기는 남매의 이야기.',
          ['라이트노벨', '판타지', '게임', '서브컬처'], _ani(19815)),
      _w('sub_book_monogatari-light-novel_2006', '바케모노가타리', 'book', 'subculture',
          '니시오 이시인', 2006,
          '괴물과 인간의 이야기를 풀어가는 대화 중심 라이트노벨.',
          ['라이트노벨', '초자연', '대화', '서브컬처'], _ani(5081)),
      _w('sub_book_spice-and-wolf_2006', '늑대와 향신료', 'book', 'subculture',
          '히세키 아야', 2006,
          '상인과 늑대신의 여행을 그린 경제 판타지 라노벨.',
          ['라이트노벨', '판타지', '경제', '로맨스'], _ani(2966)),
      _w('sub_book_slime-light-novel_2014', '전생 슬라임', 'book', 'subculture',
          '후세이', 2014,
          '슬라임으로 전생한 림루의 건국 판타지 라노벨 원작.',
          ['라이트노벨', '이세계', '슬라임', '건국'], _ani(101280)),
      _w('sub_book_mushoku-tensei-light-novel_2014', '무직전생', 'book',
          'subculture', '리덕션', 2014,
          '전생한 소년의 마법 세계 성장기 라노벨 원작.',
          ['라이트노벨', '이세계', '판타지', '성장'], _ani(108465)),
      _w('sub_book_classroom-of-the-elite_2015', '우등생의 즐거운 육아 생활… 아니 학교생활',
          'book', 'subculture', '쇼고 키누가사', 2015,
          '엘리트 학교에서 벌어지는 심리전과 성장 라노벨.',
          ['라이트노벨', '학원', '심리', '서브컬처'], _ani(98659)),
      _w('sub_book_86-light-novel_2016', '86 -에이티식스-', 'book', 'subculture',
          '아사토 아사토', 2016,
          '전쟁 속 인간과 드론의 비극을 그린 SF 라노벨.',
          ['라이트노벨', 'SF', '전쟁', '드라마'], _ani(116589)),
      _w('gen_book_dune_1965', '듄', 'book', 'generalCulture', '프랭크 허버트', 1965,
          '사막 행성 아라키스의 스파이스와 권력 투쟁 SF 고전.',
          ['SF', '고전', '정치', '명작'], _openLib('9780441172719')),
      _w('gen_book_hitchhiker-guide_1979', '은하수를 여행하는 히치하이커를 위한 안내서',
          'book', 'generalCulture', '더글러스 애덤스', 1979,
          '우주를 떠도는 코믹 SF 고전.',
          ['SF', '코미디', '고전', '우주'], _openLib('9780345391803')),
      _w('gen_book_sherlock-holmes_1887', '셜록 홈즈: 단홍색 연구', 'book',
          'generalCulture', '아서 코난 도일', 1887,
          '탐정 셜록 홈즈의 데뷔 미스터리 고전.',
          ['추리', '미스터리', '고전', '명작'], _openLib('9780141037439')),

      // ── MOVIE (+3) ──
      _w('sub_movie_demon-slayer-mugen-train_2020', '귀멸의 칼날: 무한열차편',
          'movie', 'subculture', 'ufotable', 2020,
          '탄지로 일행이 무한열차에서 귀신과 맞서는 액션 극장판.',
          ['액션', '귀신', '극장판', '서브컬처'], _tmdb('/qj429T8tzKBdQBK9NKM3FzCUWai.jpg')),
      _w('sub_movie_jujutsu-kaisen-0_2021', '주술회전 0', 'movie', 'subculture',
          'MAPPA', 2021,
          '오쿠코츠 유타의 주술 고등학교 시절을 그린 극장판.',
          ['액션', '초자연', '극장판', '서브컬처'], _tmdb('/3Arj5jAkTrR0lBr8qsR9oMtOuUY.jpg')),
      _w('gen_movie_spirited-away_2001', '센과 치히로의 행방불명', 'movie',
          'generalCulture', '미야자키 하야오', 2001,
          '신비한 세계에 빠진 소녀의 성장 판타지 애니메이션 영화.',
          ['애니메이션', '판타지', '가족', '명작'], _tmdb('/39wmItIWsg5sZaSH9zeqyiPXcVI.jpg')),

      // ── DRAMA (+3) ──
      _w('sub_drama_one-piece-live-action_2023', '원피스 (실사)', 'drama',
          'subculture', 'Matt Owens / Steven Maeda', 2023,
          '루피와 해적단의 실사 넷플릭스 시리즈.',
          ['해적', '모험', '실사', '서브컬처'], _tmdb('/4Mt7WHQykW5BcsAho9iid2f3QpB.jpg')),
      _w('gen_drama_the-mandalorian_2019', '더 만달로리안', 'drama',
          'generalCulture', 'Jon Favreau', 2019,
          '스타워즈 세계의 외로운 바운티 헌터의 모험.',
          ['SF', '스타워즈', '모험', '서사'], _tmdb('/eU1i6eHXlzMOlEqp2WwyuTvwdp.jpg')),
      _w('gen_drama_the-office-us_2005', '더 오피스', 'drama', 'generalCulture',
          'Greg Daniels', 2005,
          '평범한 회사를 배경으로 한 목업 시트콤.',
          ['코미디', '목업', '직장', '명작'], _tmdb('/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg')),
    ];

Map<String, dynamic> _w(
  String workId,
  String title,
  String category,
  String domain,
  String creator,
  int year,
  String description,
  List<String> tags,
  String posterPath,
) =>
    {
      'workId': workId,
      'title': title,
      'category': category,
      'domain': domain,
      'creator': creator,
      'releaseYear': year,
      'description': description,
      'tags': tags,
      'posterPath': posterPath,
    };
