part of 'work_detail_workspace.dart';

WorkDetailWorkspaceBody buildWorkDetailWorkspaceBody(
  _WorkDetailWorkspaceState state,
) {
  final widget = state.widget;
  return WorkDetailWorkspaceBody(
    item: state._item,
    preview: state._draft.applyDraft(),
    infoPanelWidth: widget.infoPanelWidth,
    infoPanelLocked: widget.infoPanelLocked,
    vaultLinked: AkashaFileService().vaultPath != null,
    titleCtrl: state._titleCtrl,
    posterUrlCtrl: state._posterUrlCtrl,
    bodyCtrl: state._bodyCtrl,
    fileCtrl: state._fileCtrl,
    draftRating: state._draftRating,
    draftWorkStatus: state._draftWorkStatus,
    draftMyStatus: state._draftMyStatus,
    draftHallOfFame: state._draftHallOfFame,
    draftTags: state._draftTags,
    registryTags: state._registryTags,
    isSaving: state._isSaving,
    isArchived: state._isArchived,
    isArchivedInVault: state._isArchivedInVault,
    isDirty: widget.isDirty,
    lastSavedAt: state._lastSavedAt,
    showAddToLibrary: widget.onAddToLibrary != null,
    loadingIncoming: state._connections.loadingIncoming,
    incomingPaths: state._connections.incomingPaths,
    staleLabelRecordCount: state._connections.staleLabelRecordCount,
    loadingSameDay: state._connections.loadingSameDay,
    sameDayRefs: state._connections.sameDayRefs,
    linkNeighbors: state._connections.linkNeighbors,
    loadingLinkNeighbors: state._connections.loadingLinkNeighbors,
    pageView: state._pageView,
    sectionEditorKey: state._sectionEditorKey,
    previewBodyMarkdown: state._draft.previewBodyMarkdown(),
    externalChangePending: state._externalChangePending,
    onClose: widget.onClose,
    onGoKnowledgeGraph: widget.onGoKnowledgeGraph,
    userCatalog: widget.userCatalog,
    onWikiLinkTap: widget.onWikiLinkTap,
    onRequestEntityLink: widget.onRequestEntityLink,
    onInfoWidthChanged: widget.onInfoWidthChanged,
    onToggleInfoLock: widget.onToggleInfoLock,
    onRefreshIncoming: () => state._connections.loadIncoming(
      work: state._item,
      linkIndex: widget.linkIndex,
    ),
    onOpenIncoming: state._openIncoming,
    onOpenSameDay: state._openSameDay,
    onMarkDirty: state._markDirty,
    onDraftRatingChanged: (v) => state.setState(() => state._draftRating = v),
    onDraftWorkStatusChanged: (v) =>
        state.setState(() => state._draftWorkStatus = v),
    onDraftMyStatusChanged: (v) => state.setState(() => state._draftMyStatus = v),
    onDraftHallOfFameChanged: (v) =>
        state.setState(() => state._draftHallOfFame = v),
    onDraftTagsChanged: (tags) => state.setState(() => state._draftTags = tags),
    onPosterTap: state._openPosterCorrection,
    onResetToDefaults: state._resetToDefaults,
    onSaveArchive: state._saveArchive,
    onAddToLibrary: state._handleAddToLibrary,
    onDeleteArchive: state._confirmDelete,
    onOpenLinkedEntity: state._openLinkedEntity,
    onOpenLinkedWork: state._openLinkedWork,
    onFocusSanctum: state._focusSanctumForLinks,
    onViewChanged: state._onPageViewChanged,
    onTitleChanged: state._markDirty,
    onReloadFromDisk: () => state._reloadFromDisk(),
    onDismissExternalChange: state._dismissExternalChange,
    onBodyChanged: state._markDirty,
    onFileChanged: state._markDirty,
    onOpenFileView: () => state._draft.refreshFullFileEditor(),
    onApplyTemplate: state._applyBodyTemplate,
    onExportHtml: state._exportHtml,
    onAddEntityLink:
        widget.userCatalog != null ? state._requestEntityLinkForType : null,
    onAddWorkLink: state._requestWorkLink,
  );
}
